FROM mcr.microsoft.com/dotnet/sdk:latest as build
WORKDIR /operator
COPY ./ ./
RUN dotnet publish src/Alethic.Auth0.Operator/Alethic.Auth0.Operator.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:latest as final
RUN addgroup k8s-operator && useradd -G k8s-operator operator-user
WORKDIR /operator
COPY --from=build /operator/out/ ./
RUN chown operator-user:k8s-operator -R .
USER operator-user
ENTRYPOINT [ "dotnet", "Alethic.Auth0.Operator.dll" ]
