//go:build !ignore_autogenerated

/*
Copyright 2025 SeatGeek.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0Client) DeepCopyInto(out *A0Client) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0Client.
func (in *A0Client) DeepCopy() *A0Client {
	if in == nil {
		return nil
	}
	out := new(A0Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0Client) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ClientGrant) DeepCopyInto(out *A0ClientGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ClientGrant.
func (in *A0ClientGrant) DeepCopy() *A0ClientGrant {
	if in == nil {
		return nil
	}
	out := new(A0ClientGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0ClientGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ClientGrantList) DeepCopyInto(out *A0ClientGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]A0ClientGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ClientGrantList.
func (in *A0ClientGrantList) DeepCopy() *A0ClientGrantList {
	if in == nil {
		return nil
	}
	out := new(A0ClientGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0ClientGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ClientGrantSpec) DeepCopyInto(out *A0ClientGrantSpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]V1EntityPolicyType, len(*in))
		copy(*out, *in)
	}
	if in.TenantRef != nil {
		in, out := &in.TenantRef, &out.TenantRef
		*out = new(V1TenantReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(ClientGrantConf)
		(*in).DeepCopyInto(*out)
	}
	if in.Conf != nil {
		in, out := &in.Conf, &out.Conf
		*out = new(ClientGrantConf)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ClientGrantSpec.
func (in *A0ClientGrantSpec) DeepCopy() *A0ClientGrantSpec {
	if in == nil {
		return nil
	}
	out := new(A0ClientGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ClientGrantStatus) DeepCopyInto(out *A0ClientGrantStatus) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.LastConf != nil {
		in, out := &in.LastConf, &out.LastConf
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ClientGrantStatus.
func (in *A0ClientGrantStatus) DeepCopy() *A0ClientGrantStatus {
	if in == nil {
		return nil
	}
	out := new(A0ClientGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ClientList) DeepCopyInto(out *A0ClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]A0Client, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ClientList.
func (in *A0ClientList) DeepCopy() *A0ClientList {
	if in == nil {
		return nil
	}
	out := new(A0ClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0ClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ClientSpec) DeepCopyInto(out *A0ClientSpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]V1EntityPolicyType, len(*in))
		copy(*out, *in)
	}
	if in.TenantRef != nil {
		in, out := &in.TenantRef, &out.TenantRef
		*out = new(V1TenantReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(V1SecretReference)
		**out = **in
	}
	if in.Find != nil {
		in, out := &in.Find, &out.Find
		*out = new(ClientFind)
		(*in).DeepCopyInto(*out)
	}
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(ClientConf)
		(*in).DeepCopyInto(*out)
	}
	if in.Conf != nil {
		in, out := &in.Conf, &out.Conf
		*out = new(ClientConf)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ClientSpec.
func (in *A0ClientSpec) DeepCopy() *A0ClientSpec {
	if in == nil {
		return nil
	}
	out := new(A0ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ClientStatus) DeepCopyInto(out *A0ClientStatus) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.LastConf != nil {
		in, out := &in.LastConf, &out.LastConf
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ClientStatus.
func (in *A0ClientStatus) DeepCopy() *A0ClientStatus {
	if in == nil {
		return nil
	}
	out := new(A0ClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0Connection) DeepCopyInto(out *A0Connection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0Connection.
func (in *A0Connection) DeepCopy() *A0Connection {
	if in == nil {
		return nil
	}
	out := new(A0Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0Connection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ConnectionList) DeepCopyInto(out *A0ConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]A0Connection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ConnectionList.
func (in *A0ConnectionList) DeepCopy() *A0ConnectionList {
	if in == nil {
		return nil
	}
	out := new(A0ConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0ConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ConnectionSpec) DeepCopyInto(out *A0ConnectionSpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]V1EntityPolicyType, len(*in))
		copy(*out, *in)
	}
	if in.TenantRef != nil {
		in, out := &in.TenantRef, &out.TenantRef
		*out = new(V1TenantReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Find != nil {
		in, out := &in.Find, &out.Find
		*out = new(ConnectionFind)
		(*in).DeepCopyInto(*out)
	}
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(ConnectionConf)
		(*in).DeepCopyInto(*out)
	}
	if in.Conf != nil {
		in, out := &in.Conf, &out.Conf
		*out = new(ConnectionConf)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ConnectionSpec.
func (in *A0ConnectionSpec) DeepCopy() *A0ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(A0ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ConnectionStatus) DeepCopyInto(out *A0ConnectionStatus) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.LastConf != nil {
		in, out := &in.LastConf, &out.LastConf
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ConnectionStatus.
func (in *A0ConnectionStatus) DeepCopy() *A0ConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(A0ConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ResourceServer) DeepCopyInto(out *A0ResourceServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ResourceServer.
func (in *A0ResourceServer) DeepCopy() *A0ResourceServer {
	if in == nil {
		return nil
	}
	out := new(A0ResourceServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0ResourceServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ResourceServerList) DeepCopyInto(out *A0ResourceServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]A0ResourceServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ResourceServerList.
func (in *A0ResourceServerList) DeepCopy() *A0ResourceServerList {
	if in == nil {
		return nil
	}
	out := new(A0ResourceServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0ResourceServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ResourceServerSpec) DeepCopyInto(out *A0ResourceServerSpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]V1EntityPolicyType, len(*in))
		copy(*out, *in)
	}
	if in.TenantRef != nil {
		in, out := &in.TenantRef, &out.TenantRef
		*out = new(V1TenantReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(ResourceServerConf)
		(*in).DeepCopyInto(*out)
	}
	if in.Conf != nil {
		in, out := &in.Conf, &out.Conf
		*out = new(ResourceServerConf)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ResourceServerSpec.
func (in *A0ResourceServerSpec) DeepCopy() *A0ResourceServerSpec {
	if in == nil {
		return nil
	}
	out := new(A0ResourceServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0ResourceServerStatus) DeepCopyInto(out *A0ResourceServerStatus) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.LastConf != nil {
		in, out := &in.LastConf, &out.LastConf
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0ResourceServerStatus.
func (in *A0ResourceServerStatus) DeepCopy() *A0ResourceServerStatus {
	if in == nil {
		return nil
	}
	out := new(A0ResourceServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0Tenant) DeepCopyInto(out *A0Tenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0Tenant.
func (in *A0Tenant) DeepCopy() *A0Tenant {
	if in == nil {
		return nil
	}
	out := new(A0Tenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0Tenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0TenantList) DeepCopyInto(out *A0TenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]A0Tenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0TenantList.
func (in *A0TenantList) DeepCopy() *A0TenantList {
	if in == nil {
		return nil
	}
	out := new(A0TenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *A0TenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0TenantSpec) DeepCopyInto(out *A0TenantSpec) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]V1EntityPolicyType, len(*in))
		copy(*out, *in)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(TenantAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.Init != nil {
		in, out := &in.Init, &out.Init
		*out = new(TenantConf)
		(*in).DeepCopyInto(*out)
	}
	if in.Conf != nil {
		in, out := &in.Conf, &out.Conf
		*out = new(TenantConf)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0TenantSpec.
func (in *A0TenantSpec) DeepCopy() *A0TenantSpec {
	if in == nil {
		return nil
	}
	out := new(A0TenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *A0TenantStatus) DeepCopyInto(out *A0TenantStatus) {
	*out = *in
	if in.LastConf != nil {
		in, out := &in.LastConf, &out.LastConf
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new A0TenantStatus.
func (in *A0TenantStatus) DeepCopy() *A0TenantStatus {
	if in == nil {
		return nil
	}
	out := new(A0TenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackchannelLogoutInitiators) DeepCopyInto(out *BackchannelLogoutInitiators) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.SelectedInitiators != nil {
		in, out := &in.SelectedInitiators, &out.SelectedInitiators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackchannelLogoutInitiators.
func (in *BackchannelLogoutInitiators) DeepCopy() *BackchannelLogoutInitiators {
	if in == nil {
		return nil
	}
	out := new(BackchannelLogoutInitiators)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientAuthenticationMethods) DeepCopyInto(out *ClientAuthenticationMethods) {
	*out = *in
	if in.PrivateKeyJwt != nil {
		in, out := &in.PrivateKeyJwt, &out.PrivateKeyJwt
		*out = new(PrivateKeyJwtDef)
		(*in).DeepCopyInto(*out)
	}
	if in.TlsClientAuth != nil {
		in, out := &in.TlsClientAuth, &out.TlsClientAuth
		*out = new(TlsClientAuthDef)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfSignedTlsClientAuth != nil {
		in, out := &in.SelfSignedTlsClientAuth, &out.SelfSignedTlsClientAuth
		*out = new(SelfSignedTlsClientAuthDef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientAuthenticationMethods.
func (in *ClientAuthenticationMethods) DeepCopy() *ClientAuthenticationMethods {
	if in == nil {
		return nil
	}
	out := new(ClientAuthenticationMethods)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientConf) DeepCopyInto(out *ClientConf) {
	*out = *in
	if in.SigningKeys != nil {
		in, out := &in.SigningKeys, &out.SigningKeys
		*out = make([]SigningKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ApplicationType != nil {
		in, out := &in.ApplicationType, &out.ApplicationType
		*out = new(string)
		**out = **in
	}
	if in.TokenEndpointAuthMethod != nil {
		in, out := &in.TokenEndpointAuthMethod, &out.TokenEndpointAuthMethod
		*out = new(string)
		**out = **in
	}
	if in.ClientAuthenticationMethods != nil {
		in, out := &in.ClientAuthenticationMethods, &out.ClientAuthenticationMethods
		*out = new(ClientAuthenticationMethods)
		(*in).DeepCopyInto(*out)
	}
	if in.SignedRequestObject != nil {
		in, out := &in.SignedRequestObject, &out.SignedRequestObject
		*out = new(SignedRequestObject)
		(*in).DeepCopyInto(*out)
	}
	if in.AddOns != nil {
		in, out := &in.AddOns, &out.AddOns
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedClients != nil {
		in, out := &in.AllowedClients, &out.AllowedClients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedLogoutUrls != nil {
		in, out := &in.AllowedLogoutUrls, &out.AllowedLogoutUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WebOrigins != nil {
		in, out := &in.WebOrigins, &out.WebOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InitiateLoginUri != nil {
		in, out := &in.InitiateLoginUri, &out.InitiateLoginUri
		*out = new(string)
		**out = **in
	}
	if in.Callbacks != nil {
		in, out := &in.Callbacks, &out.Callbacks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientAliases != nil {
		in, out := &in.ClientAliases, &out.ClientAliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientMetadata != nil {
		in, out := &in.ClientMetadata, &out.ClientMetadata
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.IsCustomLoginPageOn != nil {
		in, out := &in.IsCustomLoginPageOn, &out.IsCustomLoginPageOn
		*out = new(bool)
		**out = **in
	}
	if in.IsFirstParty != nil {
		in, out := &in.IsFirstParty, &out.IsFirstParty
		*out = new(bool)
		**out = **in
	}
	if in.CustomLoginPage != nil {
		in, out := &in.CustomLoginPage, &out.CustomLoginPage
		*out = new(string)
		**out = **in
	}
	if in.CustomLoginPagePreview != nil {
		in, out := &in.CustomLoginPagePreview, &out.CustomLoginPagePreview
		*out = new(string)
		**out = **in
	}
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(EncryptionKey)
		(*in).DeepCopyInto(*out)
	}
	if in.FormTemplate != nil {
		in, out := &in.FormTemplate, &out.FormTemplate
		*out = new(string)
		**out = **in
	}
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JwtConfiguration != nil {
		in, out := &in.JwtConfiguration, &out.JwtConfiguration
		*out = new(JwtConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Mobile != nil {
		in, out := &in.Mobile, &out.Mobile
		*out = new(Mobile)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LogoUri != nil {
		in, out := &in.LogoUri, &out.LogoUri
		*out = new(string)
		**out = **in
	}
	if in.OidcConformant != nil {
		in, out := &in.OidcConformant, &out.OidcConformant
		*out = new(bool)
		**out = **in
	}
	if in.OidcLogout != nil {
		in, out := &in.OidcLogout, &out.OidcLogout
		*out = new(OidcLogoutConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceServers != nil {
		in, out := &in.ResourceServers, &out.ResourceServers
		*out = make([]ClientResourceServerAssociation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Sso != nil {
		in, out := &in.Sso, &out.Sso
		*out = new(bool)
		**out = **in
	}
	if in.RefreshToken != nil {
		in, out := &in.RefreshToken, &out.RefreshToken
		*out = new(RefreshToken)
		(*in).DeepCopyInto(*out)
	}
	if in.OrganizationUsage != nil {
		in, out := &in.OrganizationUsage, &out.OrganizationUsage
		*out = new(string)
		**out = **in
	}
	if in.OrganizationRequireBehavior != nil {
		in, out := &in.OrganizationRequireBehavior, &out.OrganizationRequireBehavior
		*out = new(string)
		**out = **in
	}
	if in.CrossOriginAuthentication != nil {
		in, out := &in.CrossOriginAuthentication, &out.CrossOriginAuthentication
		*out = new(bool)
		**out = **in
	}
	if in.RequirePushedAuthorizationRequests != nil {
		in, out := &in.RequirePushedAuthorizationRequests, &out.RequirePushedAuthorizationRequests
		*out = new(bool)
		**out = **in
	}
	if in.DefaultOrganization != nil {
		in, out := &in.DefaultOrganization, &out.DefaultOrganization
		*out = new(DefaultOrganization)
		(*in).DeepCopyInto(*out)
	}
	if in.ComplianceLevel != nil {
		in, out := &in.ComplianceLevel, &out.ComplianceLevel
		*out = new(string)
		**out = **in
	}
	if in.RequireProofOfPossession != nil {
		in, out := &in.RequireProofOfPossession, &out.RequireProofOfPossession
		*out = new(bool)
		**out = **in
	}
	if in.EnabledConnections != nil {
		in, out := &in.EnabledConnections, &out.EnabledConnections
		*out = make([]V1ConnectionReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientConf.
func (in *ClientConf) DeepCopy() *ClientConf {
	if in == nil {
		return nil
	}
	out := new(ClientConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientFind) DeepCopyInto(out *ClientFind) {
	*out = *in
	if in.ClientId != nil {
		in, out := &in.ClientId, &out.ClientId
		*out = new(string)
		**out = **in
	}
	if in.CallbackUrls != nil {
		in, out := &in.CallbackUrls, &out.CallbackUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CallbackUrlMatchMode != nil {
		in, out := &in.CallbackUrlMatchMode, &out.CallbackUrlMatchMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientFind.
func (in *ClientFind) DeepCopy() *ClientFind {
	if in == nil {
		return nil
	}
	out := new(ClientFind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientGrantConf) DeepCopyInto(out *ClientGrantConf) {
	*out = *in
	if in.ClientRef != nil {
		in, out := &in.ClientRef, &out.ClientRef
		*out = new(V1ClientReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Audience != nil {
		in, out := &in.Audience, &out.Audience
		*out = new(V1ResourceServerReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientGrantConf.
func (in *ClientGrantConf) DeepCopy() *ClientGrantConf {
	if in == nil {
		return nil
	}
	out := new(ClientGrantConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientResourceServerAssociation) DeepCopyInto(out *ClientResourceServerAssociation) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientResourceServerAssociation.
func (in *ClientResourceServerAssociation) DeepCopy() *ClientResourceServerAssociation {
	if in == nil {
		return nil
	}
	out := new(ClientResourceServerAssociation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionConf) DeepCopyInto(out *ConnectionConf) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ProvisioningTicketUrl != nil {
		in, out := &in.ProvisioningTicketUrl, &out.ProvisioningTicketUrl
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Realms != nil {
		in, out := &in.Realms, &out.Realms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ShowAsButton != nil {
		in, out := &in.ShowAsButton, &out.ShowAsButton
		*out = new(bool)
		**out = **in
	}
	if in.IsDomainConnection != nil {
		in, out := &in.IsDomainConnection, &out.IsDomainConnection
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionConf.
func (in *ConnectionConf) DeepCopy() *ConnectionConf {
	if in == nil {
		return nil
	}
	out := new(ConnectionConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionFind) DeepCopyInto(out *ConnectionFind) {
	*out = *in
	if in.ConnectionId != nil {
		in, out := &in.ConnectionId, &out.ConnectionId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionFind.
func (in *ConnectionFind) DeepCopy() *ConnectionFind {
	if in == nil {
		return nil
	}
	out := new(ConnectionFind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialIdDef) DeepCopyInto(out *CredentialIdDef) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialIdDef.
func (in *CredentialIdDef) DeepCopy() *CredentialIdDef {
	if in == nil {
		return nil
	}
	out := new(CredentialIdDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOrganization) DeepCopyInto(out *DefaultOrganization) {
	*out = *in
	if in.OrganizationId != nil {
		in, out := &in.OrganizationId, &out.OrganizationId
		*out = new(string)
		**out = **in
	}
	if in.Flows != nil {
		in, out := &in.Flows, &out.Flows
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOrganization.
func (in *DefaultOrganization) DeepCopy() *DefaultOrganization {
	if in == nil {
		return nil
	}
	out := new(DefaultOrganization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionKey) DeepCopyInto(out *EncryptionKey) {
	*out = *in
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = new(string)
		**out = **in
	}
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionKey.
func (in *EncryptionKey) DeepCopy() *EncryptionKey {
	if in == nil {
		return nil
	}
	out := new(EncryptionKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwtConfiguration) DeepCopyInto(out *JwtConfiguration) {
	*out = *in
	if in.IsSecretEncoded != nil {
		in, out := &in.IsSecretEncoded, &out.IsSecretEncoded
		*out = new(bool)
		**out = **in
	}
	if in.LifetimeInSeconds != nil {
		in, out := &in.LifetimeInSeconds, &out.LifetimeInSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = new(Scopes)
		(*in).DeepCopyInto(*out)
	}
	if in.SigningAlgorithm != nil {
		in, out := &in.SigningAlgorithm, &out.SigningAlgorithm
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwtConfiguration.
func (in *JwtConfiguration) DeepCopy() *JwtConfiguration {
	if in == nil {
		return nil
	}
	out := new(JwtConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mobile) DeepCopyInto(out *Mobile) {
	*out = *in
	if in.Android != nil {
		in, out := &in.Android, &out.Android
		*out = new(MobileAndroid)
		(*in).DeepCopyInto(*out)
	}
	if in.Ios != nil {
		in, out := &in.Ios, &out.Ios
		*out = new(MobileIos)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mobile.
func (in *Mobile) DeepCopy() *Mobile {
	if in == nil {
		return nil
	}
	out := new(Mobile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MobileAndroid) DeepCopyInto(out *MobileAndroid) {
	*out = *in
	if in.AppPackageName != nil {
		in, out := &in.AppPackageName, &out.AppPackageName
		*out = new(string)
		**out = **in
	}
	if in.KeystoreHash != nil {
		in, out := &in.KeystoreHash, &out.KeystoreHash
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MobileAndroid.
func (in *MobileAndroid) DeepCopy() *MobileAndroid {
	if in == nil {
		return nil
	}
	out := new(MobileAndroid)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MobileIos) DeepCopyInto(out *MobileIos) {
	*out = *in
	if in.AppBundleIdentifier != nil {
		in, out := &in.AppBundleIdentifier, &out.AppBundleIdentifier
		*out = new(string)
		**out = **in
	}
	if in.TeamId != nil {
		in, out := &in.TeamId, &out.TeamId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MobileIos.
func (in *MobileIos) DeepCopy() *MobileIos {
	if in == nil {
		return nil
	}
	out := new(MobileIos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcLogoutConfig) DeepCopyInto(out *OidcLogoutConfig) {
	*out = *in
	if in.BackchannelLogoutUrls != nil {
		in, out := &in.BackchannelLogoutUrls, &out.BackchannelLogoutUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BackchannelLogoutInitiators != nil {
		in, out := &in.BackchannelLogoutInitiators, &out.BackchannelLogoutInitiators
		*out = new(BackchannelLogoutInitiators)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcLogoutConfig.
func (in *OidcLogoutConfig) DeepCopy() *OidcLogoutConfig {
	if in == nil {
		return nil
	}
	out := new(OidcLogoutConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateKeyJwtDef) DeepCopyInto(out *PrivateKeyJwtDef) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]CredentialIdDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateKeyJwtDef.
func (in *PrivateKeyJwtDef) DeepCopy() *PrivateKeyJwtDef {
	if in == nil {
		return nil
	}
	out := new(PrivateKeyJwtDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProofOfPossession) DeepCopyInto(out *ProofOfPossession) {
	*out = *in
	if in.Mechanism != nil {
		in, out := &in.Mechanism, &out.Mechanism
		*out = new(string)
		**out = **in
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProofOfPossession.
func (in *ProofOfPossession) DeepCopy() *ProofOfPossession {
	if in == nil {
		return nil
	}
	out := new(ProofOfPossession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefreshToken) DeepCopyInto(out *RefreshToken) {
	*out = *in
	if in.RotationType != nil {
		in, out := &in.RotationType, &out.RotationType
		*out = new(string)
		**out = **in
	}
	if in.ExpirationType != nil {
		in, out := &in.ExpirationType, &out.ExpirationType
		*out = new(string)
		**out = **in
	}
	if in.Leeway != nil {
		in, out := &in.Leeway, &out.Leeway
		*out = new(int32)
		**out = **in
	}
	if in.TokenLifetime != nil {
		in, out := &in.TokenLifetime, &out.TokenLifetime
		*out = new(int32)
		**out = **in
	}
	if in.InfiniteTokenLifetime != nil {
		in, out := &in.InfiniteTokenLifetime, &out.InfiniteTokenLifetime
		*out = new(bool)
		**out = **in
	}
	if in.IdleTokenLifetime != nil {
		in, out := &in.IdleTokenLifetime, &out.IdleTokenLifetime
		*out = new(int32)
		**out = **in
	}
	if in.InfiniteIdleTokenLifetime != nil {
		in, out := &in.InfiniteIdleTokenLifetime, &out.InfiniteIdleTokenLifetime
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefreshToken.
func (in *RefreshToken) DeepCopy() *RefreshToken {
	if in == nil {
		return nil
	}
	out := new(RefreshToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceServerAuthorizationDetail) DeepCopyInto(out *ResourceServerAuthorizationDetail) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceServerAuthorizationDetail.
func (in *ResourceServerAuthorizationDetail) DeepCopy() *ResourceServerAuthorizationDetail {
	if in == nil {
		return nil
	}
	out := new(ResourceServerAuthorizationDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceServerConf) DeepCopyInto(out *ResourceServerConf) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]ResourceServerScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SigningAlgorithm != nil {
		in, out := &in.SigningAlgorithm, &out.SigningAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningSecret != nil {
		in, out := &in.SigningSecret, &out.SigningSecret
		*out = new(string)
		**out = **in
	}
	if in.AllowOfflineAccess != nil {
		in, out := &in.AllowOfflineAccess, &out.AllowOfflineAccess
		*out = new(bool)
		**out = **in
	}
	if in.TokenLifetime != nil {
		in, out := &in.TokenLifetime, &out.TokenLifetime
		*out = new(int32)
		**out = **in
	}
	if in.TokenLifetimeForWeb != nil {
		in, out := &in.TokenLifetimeForWeb, &out.TokenLifetimeForWeb
		*out = new(int32)
		**out = **in
	}
	if in.SkipConsentForVerifiableFirstPartyClients != nil {
		in, out := &in.SkipConsentForVerifiableFirstPartyClients, &out.SkipConsentForVerifiableFirstPartyClients
		*out = new(bool)
		**out = **in
	}
	if in.VerificationLocation != nil {
		in, out := &in.VerificationLocation, &out.VerificationLocation
		*out = new(string)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.EnforcePolicy != nil {
		in, out := &in.EnforcePolicy, &out.EnforcePolicy
		*out = new(bool)
		**out = **in
	}
	if in.TokenDialect != nil {
		in, out := &in.TokenDialect, &out.TokenDialect
		*out = new(string)
		**out = **in
	}
	if in.ConsentPolicy != nil {
		in, out := &in.ConsentPolicy, &out.ConsentPolicy
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationDetails != nil {
		in, out := &in.AuthorizationDetails, &out.AuthorizationDetails
		*out = make([]ResourceServerAuthorizationDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TokenEncryption != nil {
		in, out := &in.TokenEncryption, &out.TokenEncryption
		*out = new(TokenEncryption)
		(*in).DeepCopyInto(*out)
	}
	if in.ProofOfPossession != nil {
		in, out := &in.ProofOfPossession, &out.ProofOfPossession
		*out = new(ProofOfPossession)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceServerConf.
func (in *ResourceServerConf) DeepCopy() *ResourceServerConf {
	if in == nil {
		return nil
	}
	out := new(ResourceServerConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceServerScope) DeepCopyInto(out *ResourceServerScope) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceServerScope.
func (in *ResourceServerScope) DeepCopy() *ResourceServerScope {
	if in == nil {
		return nil
	}
	out := new(ResourceServerScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScopeEntry) DeepCopyInto(out *ScopeEntry) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScopeEntry.
func (in *ScopeEntry) DeepCopy() *ScopeEntry {
	if in == nil {
		return nil
	}
	out := new(ScopeEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scopes) DeepCopyInto(out *Scopes) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = new(ScopeEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.UsersAppMetadata != nil {
		in, out := &in.UsersAppMetadata, &out.UsersAppMetadata
		*out = new(ScopeEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.Clients != nil {
		in, out := &in.Clients, &out.Clients
		*out = new(ScopeEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientKeys != nil {
		in, out := &in.ClientKeys, &out.ClientKeys
		*out = new(ScopeEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = new(ScopeEntry)
		(*in).DeepCopyInto(*out)
	}
	if in.Stats != nil {
		in, out := &in.Stats, &out.Stats
		*out = new(ScopeEntry)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scopes.
func (in *Scopes) DeepCopy() *Scopes {
	if in == nil {
		return nil
	}
	out := new(Scopes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfSignedTlsClientAuthDef) DeepCopyInto(out *SelfSignedTlsClientAuthDef) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]CredentialIdDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfSignedTlsClientAuthDef.
func (in *SelfSignedTlsClientAuthDef) DeepCopy() *SelfSignedTlsClientAuthDef {
	if in == nil {
		return nil
	}
	out := new(SelfSignedTlsClientAuthDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionCookie) DeepCopyInto(out *SessionCookie) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionCookie.
func (in *SessionCookie) DeepCopy() *SessionCookie {
	if in == nil {
		return nil
	}
	out := new(SessionCookie)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignedRequestObject) DeepCopyInto(out *SignedRequestObject) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]CredentialIdDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignedRequestObject.
func (in *SignedRequestObject) DeepCopy() *SignedRequestObject {
	if in == nil {
		return nil
	}
	out := new(SignedRequestObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigningKey) DeepCopyInto(out *SigningKey) {
	*out = *in
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Pkcs7 != nil {
		in, out := &in.Pkcs7, &out.Pkcs7
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigningKey.
func (in *SigningKey) DeepCopy() *SigningKey {
	if in == nil {
		return nil
	}
	out := new(SigningKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantAuth) DeepCopyInto(out *TenantAuth) {
	*out = *in
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(V1SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantAuth.
func (in *TenantAuth) DeepCopy() *TenantAuth {
	if in == nil {
		return nil
	}
	out := new(TenantAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantChangePassword) DeepCopyInto(out *TenantChangePassword) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Html != nil {
		in, out := &in.Html, &out.Html
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantChangePassword.
func (in *TenantChangePassword) DeepCopy() *TenantChangePassword {
	if in == nil {
		return nil
	}
	out := new(TenantChangePassword)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantConf) DeepCopyInto(out *TenantConf) {
	*out = *in
	if in.FriendlyName != nil {
		in, out := &in.FriendlyName, &out.FriendlyName
		*out = new(string)
		**out = **in
	}
	if in.SupportEmail != nil {
		in, out := &in.SupportEmail, &out.SupportEmail
		*out = new(string)
		**out = **in
	}
	if in.SupportUrl != nil {
		in, out := &in.SupportUrl, &out.SupportUrl
		*out = new(string)
		**out = **in
	}
	if in.EnabledLocales != nil {
		in, out := &in.EnabledLocales, &out.EnabledLocales
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ChangePassword != nil {
		in, out := &in.ChangePassword, &out.ChangePassword
		*out = new(TenantChangePassword)
		(*in).DeepCopyInto(*out)
	}
	if in.GuardianMfaPage != nil {
		in, out := &in.GuardianMfaPage, &out.GuardianMfaPage
		*out = new(TenantGuardianMfaPage)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultAudience != nil {
		in, out := &in.DefaultAudience, &out.DefaultAudience
		*out = new(string)
		**out = **in
	}
	if in.DefaultDirectory != nil {
		in, out := &in.DefaultDirectory, &out.DefaultDirectory
		*out = new(string)
		**out = **in
	}
	if in.ErrorPage != nil {
		in, out := &in.ErrorPage, &out.ErrorPage
		*out = new(TenantErrorPage)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceFlow != nil {
		in, out := &in.DeviceFlow, &out.DeviceFlow
		*out = new(TenantDeviceFlow)
		(*in).DeepCopyInto(*out)
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(TenantFlags)
		(*in).DeepCopyInto(*out)
	}
	if in.SessionCookie != nil {
		in, out := &in.SessionCookie, &out.SessionCookie
		*out = new(SessionCookie)
		(*in).DeepCopyInto(*out)
	}
	if in.Sessions != nil {
		in, out := &in.Sessions, &out.Sessions
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.SandboxVersion != nil {
		in, out := &in.SandboxVersion, &out.SandboxVersion
		*out = new(string)
		**out = **in
	}
	if in.IdleSessionLifetime != nil {
		in, out := &in.IdleSessionLifetime, &out.IdleSessionLifetime
		*out = new(int32)
		**out = **in
	}
	if in.SessionLifetime != nil {
		in, out := &in.SessionLifetime, &out.SessionLifetime
		*out = new(int32)
		**out = **in
	}
	if in.AllowedLogoutUrls != nil {
		in, out := &in.AllowedLogoutUrls, &out.AllowedLogoutUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionCookieMode != nil {
		in, out := &in.SessionCookieMode, &out.SessionCookieMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantConf.
func (in *TenantConf) DeepCopy() *TenantConf {
	if in == nil {
		return nil
	}
	out := new(TenantConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantDeviceFlow) DeepCopyInto(out *TenantDeviceFlow) {
	*out = *in
	if in.Charset != nil {
		in, out := &in.Charset, &out.Charset
		*out = new(string)
		**out = **in
	}
	if in.Mask != nil {
		in, out := &in.Mask, &out.Mask
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantDeviceFlow.
func (in *TenantDeviceFlow) DeepCopy() *TenantDeviceFlow {
	if in == nil {
		return nil
	}
	out := new(TenantDeviceFlow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantErrorPage) DeepCopyInto(out *TenantErrorPage) {
	*out = *in
	if in.Html != nil {
		in, out := &in.Html, &out.Html
		*out = new(string)
		**out = **in
	}
	if in.ShowLogLink != nil {
		in, out := &in.ShowLogLink, &out.ShowLogLink
		*out = new(bool)
		**out = **in
	}
	if in.Url != nil {
		in, out := &in.Url, &out.Url
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantErrorPage.
func (in *TenantErrorPage) DeepCopy() *TenantErrorPage {
	if in == nil {
		return nil
	}
	out := new(TenantErrorPage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantFlags) DeepCopyInto(out *TenantFlags) {
	*out = *in
	if in.ChangePasswordFlowV1 != nil {
		in, out := &in.ChangePasswordFlowV1, &out.ChangePasswordFlowV1
		*out = new(bool)
		**out = **in
	}
	if in.EnableClientConnections != nil {
		in, out := &in.EnableClientConnections, &out.EnableClientConnections
		*out = new(bool)
		**out = **in
	}
	if in.EnableApisSection != nil {
		in, out := &in.EnableApisSection, &out.EnableApisSection
		*out = new(bool)
		**out = **in
	}
	if in.EnablePipelineV2 != nil {
		in, out := &in.EnablePipelineV2, &out.EnablePipelineV2
		*out = new(bool)
		**out = **in
	}
	if in.EnableDynamicClientRegistration != nil {
		in, out := &in.EnableDynamicClientRegistration, &out.EnableDynamicClientRegistration
		*out = new(bool)
		**out = **in
	}
	if in.EnableCustomDomainInEmails != nil {
		in, out := &in.EnableCustomDomainInEmails, &out.EnableCustomDomainInEmails
		*out = new(bool)
		**out = **in
	}
	if in.UniversalLogin != nil {
		in, out := &in.UniversalLogin, &out.UniversalLogin
		*out = new(bool)
		**out = **in
	}
	if in.EnableLegacyLogsSearchV2 != nil {
		in, out := &in.EnableLegacyLogsSearchV2, &out.EnableLegacyLogsSearchV2
		*out = new(bool)
		**out = **in
	}
	if in.DisableClickjackProtectionHeaders != nil {
		in, out := &in.DisableClickjackProtectionHeaders, &out.DisableClickjackProtectionHeaders
		*out = new(bool)
		**out = **in
	}
	if in.EnablePublicSignupUserExistsError != nil {
		in, out := &in.EnablePublicSignupUserExistsError, &out.EnablePublicSignupUserExistsError
		*out = new(bool)
		**out = **in
	}
	if in.UseScope != nil {
		in, out := &in.UseScope, &out.UseScope
		*out = new(string)
		**out = **in
	}
	if in.AllowLegacyDelegationGrantTypes != nil {
		in, out := &in.AllowLegacyDelegationGrantTypes, &out.AllowLegacyDelegationGrantTypes
		*out = new(bool)
		**out = **in
	}
	if in.AllowLegacyROGrantTypes != nil {
		in, out := &in.AllowLegacyROGrantTypes, &out.AllowLegacyROGrantTypes
		*out = new(bool)
		**out = **in
	}
	if in.AllowLegacyTokenInfoEndpoint != nil {
		in, out := &in.AllowLegacyTokenInfoEndpoint, &out.AllowLegacyTokenInfoEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.EnableLegacyProfile != nil {
		in, out := &in.EnableLegacyProfile, &out.EnableLegacyProfile
		*out = new(bool)
		**out = **in
	}
	if in.EnableIdTokenAPI != nil {
		in, out := &in.EnableIdTokenAPI, &out.EnableIdTokenAPI
		*out = new(bool)
		**out = **in
	}
	if in.EnableIdTokenImplicitGrant != nil {
		in, out := &in.EnableIdTokenImplicitGrant, &out.EnableIdTokenImplicitGrant
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantFlags.
func (in *TenantFlags) DeepCopy() *TenantFlags {
	if in == nil {
		return nil
	}
	out := new(TenantFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantGuardianMfaPage) DeepCopyInto(out *TenantGuardianMfaPage) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Html != nil {
		in, out := &in.Html, &out.Html
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantGuardianMfaPage.
func (in *TenantGuardianMfaPage) DeepCopy() *TenantGuardianMfaPage {
	if in == nil {
		return nil
	}
	out := new(TenantGuardianMfaPage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TlsClientAuthDef) DeepCopyInto(out *TlsClientAuthDef) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]CredentialIdDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TlsClientAuthDef.
func (in *TlsClientAuthDef) DeepCopy() *TlsClientAuthDef {
	if in == nil {
		return nil
	}
	out := new(TlsClientAuthDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenEncryption) DeepCopyInto(out *TokenEncryption) {
	*out = *in
	if in.EncryptionKey != nil {
		in, out := &in.EncryptionKey, &out.EncryptionKey
		*out = new(TokenEncryptionKey)
		(*in).DeepCopyInto(*out)
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenEncryption.
func (in *TokenEncryption) DeepCopy() *TokenEncryption {
	if in == nil {
		return nil
	}
	out := new(TokenEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenEncryptionKey) DeepCopyInto(out *TokenEncryptionKey) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Algorithm != nil {
		in, out := &in.Algorithm, &out.Algorithm
		*out = new(string)
		**out = **in
	}
	if in.KeyId != nil {
		in, out := &in.KeyId, &out.KeyId
		*out = new(string)
		**out = **in
	}
	if in.Pem != nil {
		in, out := &in.Pem, &out.Pem
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenEncryptionKey.
func (in *TokenEncryptionKey) DeepCopy() *TokenEncryptionKey {
	if in == nil {
		return nil
	}
	out := new(TokenEncryptionKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1ClientReference) DeepCopyInto(out *V1ClientReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1ClientReference.
func (in *V1ClientReference) DeepCopy() *V1ClientReference {
	if in == nil {
		return nil
	}
	out := new(V1ClientReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1ConnectionReference) DeepCopyInto(out *V1ConnectionReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1ConnectionReference.
func (in *V1ConnectionReference) DeepCopy() *V1ConnectionReference {
	if in == nil {
		return nil
	}
	out := new(V1ConnectionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1ResourceServerReference) DeepCopyInto(out *V1ResourceServerReference) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1ResourceServerReference.
func (in *V1ResourceServerReference) DeepCopy() *V1ResourceServerReference {
	if in == nil {
		return nil
	}
	out := new(V1ResourceServerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1SecretReference) DeepCopyInto(out *V1SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1SecretReference.
func (in *V1SecretReference) DeepCopy() *V1SecretReference {
	if in == nil {
		return nil
	}
	out := new(V1SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1TenantReference) DeepCopyInto(out *V1TenantReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1TenantReference.
func (in *V1TenantReference) DeepCopy() *V1TenantReference {
	if in == nil {
		return nil
	}
	out := new(V1TenantReference)
	in.DeepCopyInto(out)
	return out
}
