apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth0-operator-role
  labels: {{- include "auth0-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - a0tenants
  - a0clients
  - a0resourceservers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - '*'
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - a0clientgrants
  - a0connections
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - a0tenants/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - a0clients/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - a0resourceservers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - a0clientgrants/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - a0connections/status
  verbs:
  - get
  - update
  - patch
